#server:
#  port: 8089
app:
  wallet:
    url: http://wallet-service:8081
  #jwt
  jwt:
    secret: "FinPayPlatformSecretKey2026SuperSecureAndLongEnoughForHS256"
    expiration-ms: 86400000 # Token có hiệu lực trong 24 giờ (tính bằng mili-giây)
#postgresql
spring:
  datasource:
    url: jdbc:postgresql://finpay-postgres:5432/finpay_user_db
#    url: jdbc:postgresql://localhost:5432/finpay_user_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
